---
apiVersion: apps/v1
#kind: DaemonSet
kind: Deployment
metadata:
  name: biblify-frontend
  namespace: egs7
spec:
  replicas: 2
  selector:
    matchLabels:
      app: biblify-frontend
  template:
    metadata:
      labels:
        app: biblify-frontend
    spec:
      containers:
      - name: biblify-frontend
        image: registry.deti:5000/biblify/frontend:2022062201
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: biblify-frontend
  namespace: egs7
spec:
  ports:
  - port: 3000
    targetPort: 8081
  selector:
    app: biblify-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: biblify-frontend
  namespace: egs7
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: biblify-frontend.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: biblify-frontend
            port: 
              number: 3000
