apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: biblify
  namespace: egs7
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/custom-response-headers: "Access-Control-Allow-Origin:*||Access-Control-Allow-Methods:GET,POST,OPTIONS||Access-Control-Allow-Headers:DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range||Access-Control-Expose-Headers:Content-Length,Content-Range"
spec:
  rules:
  - host: biblify-stock.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stock
            port: 
              number: 30099
  - host: biblify-frontend.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port: 
              number: 80
  - host: biblify-auth.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authapi
            port: 
              number: 8000
              
              
                      # resources:
        #   requests:
        #     memory: "32Mi"
        #     cpu: "10m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
